title: BobTalksTech
description: See what's new on the <a href="https://www.youtube.com/channel/UCEZvFXNuS2ZfzXO4I2z-yMg" title="See what new on YouTube" target="_blank">BobTalksTech YouTube channel</a>
copyright: (c) 2020, Bob Watson and BobTalksTech.com. All rights reserved.
disclaimer: The views, thoughts, and opinions presented on this site are those of the author alone and do not necessarily represent the views of the author's employer or any other individual or organization.
theme: jekyll-theme-minimal
author: "Bob"
baseurl: ""
url: "https://bobtalkstech.com"
google_analytics: UA-58134115-5
google_adsense: ca-pub-4973712141072148
include: ['_posts']
show_github: false
show_downloads: false
social:
  show: true
  heading: "Follow me on"
  youtube: https://www.youtube.com/channel/UCEZvFXNuS2ZfzXO4I2z-yMg
  twitch: https://www.twitch.tv/bobtalkstech
  facebook: https://www.facebook.com/bobtalkstech
  instagram: https://www.instagram.com/bobtalkstech/
  twitter: https://twitter.com/bobtalkstech/
  github: https://github.com/bobtalkstech
